### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by almereyda** [jankovicsandras/imagetracerjs#13]
This seems useful for generic conversion of bitmaps into SVG.

Unfortunately it does not allow to run as a standalone program, other than [the Java version](https://github.com/jankovicsandras/imagetracerjava#running-as-a-standalone-program).

To use the better color quantization algorithm from the JavaScript version in scripts, it would be helpful to call the contained logic from a command line interface.

**Comment by jankovicsandras** [comment]
Hi,

I haven't made a CLI version for JavaScript (yet), but you can make it! :)

1. Please install [Node.js](https://nodejs.org) and open a terminal or the "Node.js command prompt" on Windows.
2. Go to the directory `imagetracerjs/nodetest` and run `node nodetest`
3. It should create a test.svg file and return with the message "test.svg was saved!"

If this works, then you need only 3 very small things to change in the [nodetest.js](https://github.com/jankovicsandras/imagetracerjs/blob/master/nodetest/nodetest.js) file.

4. You need a command line parser, this will pass the command line arguments to the `nodetest.js` as JavaScript variables. These packages seem to be popular on Npmjs.com, but there are many other alternatives, it's a good idea to search around a bit. I haven't tried these, but I think they will work:

[https://www.npmjs.com/package/minimist](https://www.npmjs.com/package/minimist)

[https://www.npmjs.com/package/yargs](https://www.npmjs.com/package/yargs)

[https://www.npmjs.com/package/commander](https://www.npmjs.com/package/commander)

5. You should change the [input file path (ca. line 13)](https://github.com/jankovicsandras/imagetracerjs/blob/79fd2f115900af3ee0b93f9e65176a3b759bf59b/nodetest/nodetest.js#L13) to use a filename from a CLI argument.

6. You need to change the [options object (ca. line 27)](https://github.com/jankovicsandras/imagetracerjs/blob/79fd2f115900af3ee0b93f9e65176a3b759bf59b/nodetest/nodetest.js#L27) to something you get from the CLI arguments.

Then you will get something like this:
`node nodetest -inputfile myfile.jpg -ltres 0.1 -numberofcolors 50  ... etc. `

**Please let me know if this works or not!**

Miguel Lemos adapted an [ImageMagick octree based color quantization algorithm](https://github.com/miguelemosreverte/imagetracerjava/blob/master/jankovicsandras/imagetracer/Quantize.java) to the Java version. I don't think it can be used with Node.js CLI directly, but it should be possible to port it to JavaScript. I'll consider doing this or making a new octree based algorithm if there's interest.
It's also theoretically possible to use the Java version with the better color quantization somehow to export the palette, and then use the JavaScript version with Node.js CLI and import the palette, but this can be complex.

So the better color quantization is not available for JavaScript now, but might be in the future.

**Comment by jankovicsandras** [comment]
I made a Node.js CLI in version 1.2.3.

**Comment by almereyda** [comment]
Nice, many thanks. Very much appreciated.
