### ISSUE TITLE
Transparent areas are made in images without any transparency

### ISSUE THREAD

**Issue by quinton-ashley** [jankovicsandras/imagetracerjs#19]
I'm wondering if there might be an option for stacking SVG shapes so there's no transparent background showing up.  Right now I'm getting a lot of transparent spots in the SVG files so when I export using a black background it shows through a lot.  Maybe the background could be filled by the original image?
![z001010](https://user-images.githubusercontent.com/20031683/37694282-5183f6b8-2c9c-11e8-9b63-c8ce61040e28.jpg)
![z001010](https://user-images.githubusercontent.com/20031683/37694290-5a6e39dc-2c9c-11e8-8201-099105ffc66a.png)
Here's what an inkscape render would look like if image tracer output an svg using the original image as the background:
![z001010](https://user-images.githubusercontent.com/20031683/37694479-ef74a394-2c9d-11e8-88e1-980b5794fe95.png)

**Comment by jankovicsandras** [comment]
Hi,

I recommend you setting ```options.pathomit = 0``` and maybe ```options.strokewidth = 2``` (or more).
You can also try the older [1.1.2 version](https://github.com/jankovicsandras/imagetracerjs#legacy-112-version) ( [Readme for 1.1.2](https://github.com/jankovicsandras/imagetracerjs/blob/master/README_v1.1.2.md) ) : that is stack based, so [it can't have transparent holes](https://github.com/jankovicsandras/imagetracerjs/blob/master/docimages/transparency_problem.png).

Please give me a feedback whether these work or not! ☺

**Comment by jankovicsandras** [comment]
I hope these worked, please reopen the issue if not.

**Comment by quinton-ashley** [comment]
Thanks for adding the stack based version as an option in the latest version!
