### ISSUE TITLE
Used library in VectorCam

### ISSUE THREAD

**Issue by jywarren** [jankovicsandras/imagetracerjs#2]
http://jywarren.github.io/vectorcam/ - https://github.com/jywarren/vectorcam

Thanks so much for your super great library! I put this project together in one day. http://unterbahn.com/2015/08/vectorizing-sketches-and-photos-with-your-smartphoneweb-browser/

Didn't know how else to get in touch so feel free to close this issue, but THANKS!

**Comment by jankovicsandras** [comment]
Thanks for your contribution with the Bower manifest file! I'm happy that you made VectorCam, it looks like an interesting and useful application. 

My email address is: jankovicsandras@gmail.com
