### ISSUE TITLE
Input not filename

### ISSUE THREAD

**Issue by Portur** [jankovicsandras/imagetracerjs#20]
Hi,

Is it possible to provide the image itself rather than the filename/path?
eg. a previous request wold be to get it and then after is to vectorize it.

`let image = response.body || fs.readFile(imagePath, 'utf8')`
then
`ImageTracer.imageToSvg(image , callback)`

**Comment by Portur** [comment]
I think the method for this is 
`imageTracer.imagedataToTraceData(image, options, traceData => { alert(traceData) })`.
My understanding was this was CLI only.

**Comment by jankovicsandras** [comment]
Hi,

Yes, it should work, only it is not using a callback function, but returning a value directly:

```javascript
// imgd is an object like https://developer.mozilla.org/en-US/docs/Web/API/ImageData object, with .data .height .width fields

// Synchronous tracing to SVG string with options object
var svgstr = ImageTracer.imagedataToSVG( imgd, { scale:5 } );

// Synchronous tracing to tracedata with option preset
var tracedata = ImageTracer.imagedataToTracedata( imgd, 'Detailed' );
```
