### ISSUE TITLE
Ignore White / monotone svg

### ISSUE THREAD

**Issue by skaggetse** [jankovicsandras/imagetracerjs#26]
Thanks for this great script. I have a question though:

When tracing pixelimages to vector in Adobe Illustrator, there's an option to "Ignore white".
This means there will be no white box around an object.

I'm trying to achieve the same output with this script, but the palette-options seems to only change the input image before the tracing part, so it does not output correctly.

This is my image:
![img](https://user-images.githubusercontent.com/10872977/52882062-c4d17f80-3166-11e9-9e02-81aeb05a783f.jpg)

This is my options:
        options = { colorsampling:false, colorquantcycles:1, 
            pal:[
                {r:0,g:0,b:0,a:255},
                {r:255,g:255,b:255,a:255}
            ] 
        };

This is the result:

<img width="581" alt="skarmavbild 2019-02-15 kl 21 17 00" src="https://user-images.githubusercontent.com/10872977/52882147-0eba6580-3167-11e9-9386-466362c8d5b2.png">

Now, if I change the white color in my palette to transparent( {r:255,g:255,b:255,a:0}), this happens:

<img width="610" alt="skarmavbild 2019-02-15 kl 21 17 52" src="https://user-images.githubusercontent.com/10872977/52882180-2bef3400-3167-11e9-8d0f-7b0ee9f6013c.png">

This is what I was expecting to get:

<img width="628" alt="skarmavbild 2019-02-15 kl 21 19 02" src="https://user-images.githubusercontent.com/10872977/52882243-57721e80-3167-11e9-8332-2ced8eda3de8.png">

Is it possible to get my expected output?

**Comment by jankovicsandras** [comment]
Hi,

Yes, it's possible, you just need to change the palette after tracing, but before rendering. ```imageToTracedata``` is probably the easiest way to do this. Here's an example with some boilerplate HTML:

```javascript
<html>
<body onload="onload_init()">
<script>

function onload_init(){

	var options = { colorsampling:false, colorquantcycles:1,
		pal:[
			{r:0,g:0,b:0,a:255},
			{r:255,g:255,b:255,a:255}
		]
	};
	
	ImageTracer.imageToTracedata(
		'cat.jpg',
		function(tracedata){
			
			// loop on palette, set white-like colors transparent
			for(var i=0; i<tracedata.palette.length; i++){
				
				var whiteness = tracedata.palette[i].r+tracedata.palette[i].g+tracedata.palette[i].b;
				var whitetreshold = 600; // r>=200 g>=200 b>=200 will be considered white
				
				if(whiteness>=whitetreshold){
					// tracedata.layers[i] can be removed with array.splice()
					// but we will render it with transparency for simplicity
					tracedata.palette[i].r = 0;
					tracedata.palette[i].g = 0;
					tracedata.palette[i].b = 0;
					tracedata.palette[i].a = 0;
				}
				
			}// End of loop on palette
			
			// render and append SVG string to body
			ImageTracer.appendSVGString(
				ImageTracer.getsvgstring( tracedata, options )
			);
			
		},// End of imageToTracedata callback()
		
		options
		
	);// End of ImageTracer.imageToTracedata()
	
}// End of onload_init()

</script>
<script src="imagetracer_v1.2.5.js"></script>
</body>
</html>
```

I hope this answers your question, you can reopen this issue if you need more help. :)
