### ISSUE TITLE
enable github pages and add links to examples in README 

### ISSUE THREAD

**Issue by cancerberoSgx** [jankovicsandras/imagetracerjs#27]
Just enabling github pages (on master branch root folder), will enable users to quickly experience this awesome library examples (I've done it in my fork just for this issue) https://cancerberosgx.github.io/imagetracerjs/imagetracer_options_gallery.html
https://cancerberosgx.github.io/imagetracerjs/imagetracer_examples.html

After that, with more time, would be awesome to have a minimal playground so users are able to adjust options and transform its own images. 

Thanks, great project!

**Comment by jankovicsandras** [comment]
I think it is enabled already, but you're right, it should be more documented, and I should add a simpler playground page.

[http://jankovicsandras.github.io/imagetracerjs/imagetracer_test_automation.html](http://jankovicsandras.github.io/imagetracerjs/imagetracer_test_automation.html)
