### ISSUE TITLE
Types of Image Files

### ISSUE THREAD

**Issue by isangieri** [jankovicsandras/imagetracerjs#3]
What types of image files have you traced so far? What are limitations of using certain filetypes?

**Comment by jankovicsandras** [comment]
imagetracer.js uses the standard HTML5 <canvas> and JavaScript functions in [**loadImage()**](https://github.com/jankovicsandras/imagetracerjs/blob/master/imagetracer_v1.0.4.js#L938) , so the supported file types depend on the [browser](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support) . JPEG, GIF, PNG and BMP should work. If you would like to trace other formats, e.g. [PCX](https://en.wikipedia.org/wiki/PCX) which might not be supported by the browser, try to load it into an [ImageData object](https://developer.mozilla.org/en/docs/Web/API/ImageData) and call **imagedataToSVG()** or **imagedataToTracedata()** . Please note that there is no built in check on image size, so trying to trace very big images might cause out-of-memory error.
