### ISSUE TITLE
How to use in Node.js 

### ISSUE THREAD

**Issue by Shekharrajak** [jankovicsandras/imagetracerjs#30]
Hello,

I am trying to use this package in node.js program. I am following the steps given at https://github.com/jankovicsandras/imagetracerjs#simple-nodejs-converting-example but I didn't understand what to require instead of `require( __dirname + '/../imagetracer_v1.2.5' );`. 

Can you please help me in this ?

**Comment by jankovicsandras** [comment]
Hi,

What kind of error message do you get? Wrong path / imagetracer_v.1.2.5 not found?
Have you downloaded the package? I recommend downloading it to the current directory and use it with a local path.

Please note that PNGReader.js is in the package to be "batteries included", but not a part of ImageTracer project. You need either this or some other library to load an image file to an ImageData object.
