### ISSUE TITLE
Option to disallow splines/curves, etc. (possibility to use straight lines only)

### ISSUE THREAD

**Issue by Brixomatic** [jankovicsandras/imagetracerjs#32]
Reason: I tied vectorizing an image and that worked pretty well (it's a male silhouette), unfortunately I can't switch off drawing curves, but I'd like the shape aproximated by straight lines only.
As I understood the source, it tries to approximate with a line first, then some sort of curved shape and if that fails tries to recursively break the path up.
This should be optional.

**Comment by jankovicsandras** [comment]
Hi,

Have you tried the [```'sharp'``` option preset](https://github.com/jankovicsandras/imagetracerjs/blob/master/options.md) or using very small ```qtres```, e. g. ```0.0001``` ? This will practically force straight lines. 

You can also comment out everything between [lines 783](https://github.com/jankovicsandras/imagetracerjs/blob/21b1d9bd21a374fe35620ece1058a55307e111e0/imagetracer_v1.2.5.js#L783) [- 805](https://github.com/jankovicsandras/imagetracerjs/blob/21b1d9bd21a374fe35620ece1058a55307e111e0/imagetracer_v1.2.5.js#L805) to deactivate Q splines. Or hack [svgpathstring()](https://github.com/jankovicsandras/imagetracerjs/blob/21b1d9bd21a374fe35620ece1058a55307e111e0/imagetracer_v1.2.5.js#L844) to always render only L segments.

Can you test and give me feedback whether some of these solve your problem?

**Comment by Brixomatic** [comment]
Using very small qrtes does the trick, thank you.
