### ISSUE TITLE
Does this library require canvas?

### ISSUE THREAD

**Issue by velara3** [jankovicsandras/imagetracerjs#33]
Does this library require canvas? 

I'm attempting to work around lack of canvas and ImageData object [here](https://stackoverflow.com/questions/58465010/how-to-supply-the-correct-data-when-imagedata-is-not-available).

**Comment by jankovicsandras** [comment]
Hi,

No, it doesn't require canvas, but you need to load and decode the image into an ImageData-like object. It has width, height and data: a one-dimensional array with R G B A values.

```javascript
var myImagedata = { width: ... , height: ... , data: [ R,G,B,A, R,G,B,A, ... ] };
```

I tried to answer your Stackoverflow question also.

**Comment by velara3** [comment]
Thanks @jankovicsandras! I think that might be it. I'll work on it when I get back to work.

**Comment by jankovicsandras** [comment]
OK. I'm closing this Issue now, but you can reopen it, if it won't work or you have more questions.
