### ISSUE TITLE
not working on mobile?

### ISSUE THREAD

**Issue by mrjizz** [jankovicsandras/imagetracerjs#36]
as far as I can see I'm getting this error

Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

image loads fine on all desktop browsers I have tested but not on mobile?

my test code:
"<script src="/imagetracer_v1.2.5.js"></script>

<div id="svgcontainer"></div>
<img src="/babyface.jpg">
<canvas></canvas>

<script>
var the_image = '/babyface.jpg';

var options = {
    colorquantcycles : 1,
    pathomit : 11
};

options.pal = [{r:255,g:255,b:255,a:255}, {r:0,g:0,b:0,a:255}];

    ImageTracer.imageToSVG(

	the_image, 
	
	function(svgstr){ ImageTracer.appendSVGString( svgstr, 'svgcontainer' ); 
	    
	}, 
	
	options
	
);

</script>"

**Comment by btxtiger** [comment]
Check your file paths, `/` only points to a directory. But you are requiring files here. So either use `./imagetracer.js` and `./babyface.jpg` or just remove the prepending slash to `imagetracer.js`, `babyface.jpg`.

**Comment by mrjizz** [comment]
> Check your file paths, `/` only points to a directory. But you are requiring files here. So either use `./imagetracer.js` and `./babyface.jpg` or just remove the prepending slash to `imagetracer.js`, `babyface.jpg`.

this doesn't work as it goes server/domain/file? (again working fine on desktop browsers not on mobile just)

as iv been looking into it, iv noticed a few issues where mobile browsers won't show SVG? any experience with that?

also with a further investigation (not too clued in on debugging android browser?), the error may not be from 'imagetracer' but as I say, just the fact the mobile browser is not displaying the SVG?

**Comment by mrjizz** [comment]
hold my horses!, tried changing file paths as you said then reverted back and now it's firing the same error on desktop now, dam!, I didn't even change anything else.

sorry for noobness but would I have to call my js files from the main folder then?

> Check your file paths, `/` only points to a directory. But you are requiring files here. So either use `./imagetracer.js` and `./babyface.jpg` or just remove the prepending slash to `imagetracer.js`, `babyface.jpg`.

hold my horses!, tried changing file paths as you said then reverted back and now it's firing the same error on desktop now, dam!, I didn't even change anything else.

sorry for noobness but would I have to call my js files from the main folder then?

**Comment by mrjizz** [comment]
> > > Check your file paths, `/` only points to a directory. But you are requiring files here. So either use `./imagetracer.js` and `./babyface.jpg` or just remove the prepending slash to `imagetracer.js`, `babyface.jpg`.
> > 
> > 
> > this doesn't work as it goes server/mydomainfolder/file? (again working fine on desktop browsers not on mobile just)
> > as iv been looking into it, iv noticed a few issues where mobile browsers won't show SVG? any experience with that?
> > also with a further investigation (not too clued in on debugging android browser?), the error may not be from 'imagetracer' but as I say, just the fact the mobile browser is not displaying the SVG?
> 
> hold my horses!, tried changing file paths as you said then reverted back and now it's firing the same error on desktop now, dam!, I didn't even change anything else.
> 
> sorry for noobness but would I have to call my js files from the main folder then?
> 
> (im running apache shared hosting with wordpress install if that helps any)

Eureka!, you can probably forget everything iv said :/

it was an HTTP vs https problem (ie being sent to HTTP instead of the https address)

**Comment by jankovicsandras** [comment]
Hi,

As I understand, this Issue is solved. Great! :)

I recommend you checking out [```options.corsenabled```](https://github.com/jankovicsandras/imagetracerjs/blob/master/options.md#tracing) also or more on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image) .
