### ISSUE TITLE
How can i create a black/white style image?

### ISSUE THREAD

**Issue by gbin1** [jankovicsandras/imagetracerjs#4]
How to generate a black/white style image with this library? thanks

**Comment by jankovicsandras** [comment]
For black and white images, use
```javascript
options = { colorsampling:false, colorquantcycles:1, numberofcolors:2  };
```
(You can set numberofcolors < 8 for smoother grayscale and set other parameters as well.)

----

More info:

`colorsampling:false, colorquantcycles:1` will turn off colorsampling and RGBA clustering in color quantization.
This means 
1. a generated palette will be used 
2. as it is, without trying to adjust the colors to the image.

The `generatepalette(numberofcolors)` function will return a grayscale palette if `numberofcolors < 8`. So this will generate a 7 color grayscale:
```javascript
options = { colorsampling:false, colorquantcycles:1, numberofcolors:7  };
```

You can also add a custom palette, here's an example for 11 color grayscale:
```javascript
options = { colorsampling:false, colorquantcycles:1, 
    pal:[
           {r:0,g:0,b:0,a:255},
           {r:25,g:25,b:25,a:255},
           {r:50,g:50,b:50,a:255},
           {r:75,g:75,b:75,a:255},
           {r:100,g:100,b:100,a:255},
           {r:125,g:125,b:125,a:255},
           {r:150,g:150,b:150,a:255},
           {r:175,g:175,b:175,a:255},
           {r:200,g:200,b:200,a:255},
           {r:225,g:225,b:225,a:255},
           {r:250,g:250,b:250,a:255}
      ] 
};
```
When you add a custom palette, `numberofcolors` is not required, will be ignored.

**Comment by gbin1** [comment]
One more question,  is it possible to create cartoon style black/white image?
Original image:
[original image](http://img.witmart.com/job/2016-06/22/pub/20160622233307_576b587346ede.jpg)
Cartoon style image:
[Cartoon style image](http://img.witmart.com/job/2016-06/22/pub/20160622233305_576b5871279be.jpg)
