### ISSUE TITLE
Issue with tracing

### ISSUE THREAD

**Issue by r-zammit** [jankovicsandras/imagetracerjs#40]
Hi, 
I'm getting this issue when tracing simple curved and diagonal lines. Do you have any idea what might be causing this? I went and tried the same image with Vector Magic and it traced the curves and diagonals perfectly so it should be doable.

<img width="165" alt="Screen Shot 2020-05-08 at 2 17 30 PM" src="https://user-images.githubusercontent.com/12617956/81435986-b0e0b780-9136-11ea-9dd2-2bcf9e1a43c9.png">

Thanks!

**Comment by jankovicsandras** [comment]
Hi,

Can you please upload the original image also and your options object/preset? I think the color quantization splits the gradient to two colors: the light purple spots should be the in the same purple shape. This can be fixed by tweeking the color quantization parameters. ```ltres = 0.01``` and  ```qtres = 1``` might also help.

**Comment by r-zammit** [comment]
Hi there,

Changing the qtres and ltres and changing the color palette to only 2 colors helped a bit, but it's still not tracing curved or diagonal paths properly. 

Here's the new options object I'm using: 
var opts = {
                      pathomit:35, //Changing this to 1 makes the P more jagged 
                      qtres: 0.5,
                      ltres: 0.1, 
                      numberofcolors: 2
                    }

Here are the 2 input images I'm testing it on:
![W](https://user-images.githubusercontent.com/12617956/81499300-9aeb0800-9298-11ea-95a9-7971dd6fa663.png)
![P](https://user-images.githubusercontent.com/12617956/81499304-a50d0680-9298-11ea-9579-77440884f559.png)

And here is the svg output
<img width="225" alt="Screen Shot 2020-05-10 at 8 33 16 AM" src="https://user-images.githubusercontent.com/12617956/81499338-e998a200-9298-11ea-9c3a-0d86c8215ba4.png">
<img width="523" alt="Screen Shot 2020-05-10 at 8 28 05 AM" src="https://user-images.githubusercontent.com/12617956/81499348-f6b59100-9298-11ea-8843-df3f903fae37.png">

**Comment by r-zammit** [comment]
HI there, have you been able to make any headway on this issue?

**Comment by jankovicsandras** [comment]
Hi,

I don't see any problem with ImageTracer itself, but I recommend you experimenting with  ```options``` or doing some preprocessing with another image manipulation program. You can try to remove / flatten the smoothed edges of the letters for example.

I tried these options and got OK results, I'm not sure you can get much better quality from these input images.

W

```"sharp"```

```{"qtres":0.01,"linefilter":true,"rightangleenhance":true,"strokewidth":0}```

![W](https://user-images.githubusercontent.com/12699003/83324505-ea07d580-a265-11ea-9533-ba585b941701.png)


P

```"curvy"```

```{"ltres":0.01,"linefilter":true,"rightangleenhance":true,"strokewidth":0}```

```{"ltres":0.01,"linefilter":true,"rightangleenhance":true,"strokewidth":0,"numberofcolors":2}```

![P](https://user-images.githubusercontent.com/12699003/83324510-ef652000-a265-11ea-8c60-66dbaa26c1b0.png)
