### ISSUE TITLE
Handle (absolute) paths in CLI correctly

### ISSUE THREAD

**Issue by der-On** [jankovicsandras/imagetracerjs#42]
Currently the `nodecli.js` script requires paths to be set relative to the `nodecli` directory.

Instead change https://github.com/jankovicsandras/imagetracerjs/blob/master/nodecli/nodecli.js#L58
to
```
infilename, // Input file path
```
and https://github.com/jankovicsandras/imagetracerjs/blob/master/nodecli/nodecli.js#L76
to
```
outfilename, // Output file path
```

This will do two things:

1. It will resolve paths relative to the current working directory instead of the `nodecli` directory (expected result for the user)
2. It will resolve absolute paths, or paths with protocolls in front that are supported by nodes `fs` module.

**Comment by jankovicsandras** [comment]
Hi,

This should be fixed in version 1.2.6, please test.
