### ISSUE TITLE
How to create cartoon style black/white image by imagetracerJS?

### ISSUE THREAD

**Issue by gbin1** [jankovicsandras/imagetracerjs#5]
Here is a image, i need to use imagetracerJS to convert it to cartoon style image as below:
Original image:
[original image](http://img.witmart.com/job/2016-06/22/pub/20160622233307_576b587346ede.jpg)

TO

Cartoon style image:
[Cartoon style image](http://img.witmart.com/job/2016-06/22/pub/20160622233305_576b5871279be.jpg)

**Comment by jankovicsandras** [comment]
Hi,

1. Copy your original image and ```imagetracer_v1.1.1.js``` to a folder.
2. Create a new text file, copy and paste the following code into it, and save it as ```convert.html```
3. Open ```convert.html``` in your browser, wait, and Right-click + Save Link As on the appearing link.
```javascript
<html>
<body>
<script src="imagetracer_v1.1.1.js"></script>
<script>
	ImageTracer.imageToSVG( // converting image to SVG
			
			'20160622233307_576b587346ede.jpg', // your image
			
			function(svgstr){ // this function will make a download link to the created SVG
				document.body.innerHTML += '<a href="data:image/svg+xml;base64,'+ 
					btoa(svgstr)+ // Base64 encoding the SVG string
					'" target="_blank">Right-click on this + Save Link As</a>';
			},
			
			{ colorsampling:false, colorquantcycles:1, numberofcolors:2  } // options for black and white

	);// End of ImageTracer.imageToSVG()
</script>
</body>
</html>
```

But I think the Cartoon style example was made with some kind of edge detection, so you might need something else for this effect. I recommend [GIMP](https://www.gimp.org/) for this.
More info:
[Search Google for GIMP edge detection](https://www.google.no/search?q=gimp+edge+detection)
[Wikipedia article about edge detection](https://en.wikipedia.org/wiki/Edge_detection)
