### ISSUE TITLE
Setting the max number of paths

### ISSUE THREAD

**Issue by velara3** [jankovicsandras/imagetracerjs#52]
I've been reading through the options and the source and I thought I saw something that allowed me to set the maximum number of paths but now I can't seem to find. 

Is there an option to set the max number of paths?

**Comment by jankovicsandras** [comment]
Hi,

No, sorry this was never an option. Why do you need this?

For example, if you have one triangle on a solid background on the picture, you will probably get 2 paths (the triangle and the background). If you have 500 separate, not touching triangles on the picture, you would get 501 paths. If there would be an option that forces e.g. max 100 paths, what would happen the rest, the remaining 401 triangles?

But it's possible to achieve this, if you want! :)

You can process tracedata (here's an example https://github.com/jankovicsandras/imagetracerjs/issues/25) , count the paths and splice the not required paths out of the array.

Or you can hack ```getsvgstring()``` around Line 990:

```javascript
		// Adding SVG <path> string
		if( !tracedata.layers[lcnt][pcnt].isholepath ){
			svgstr += _this.svgpathstring( tracedata, lcnt, pcnt, options );
			renderedcounter ++;
			if( renderedcounter > maxnumberofpaths ){ break; }
		}
```

**Comment by jankovicsandras** [comment]
I hope this helped, feel free to reopen the issue if you have further questions.

**Comment by velara3** [comment]
Simply cutting off the excess paths does exactly what it sounds like. It stops the drawing of the remaining paths and there is less than a full image so I'm reducing the colors to lower the path count. This seems to work. Do you have any other suggestions to reduce the path count?

**Comment by jankovicsandras** [comment]
I think these options might help, but it depends on your input and what your goal is.

"Big" ```ltres``` and ```qtres``` values, e. g. > 4+ will not get fewer paths, but fewer segments in the paths, so might help reduce SVG size.

"Big" ```pathomit``` values, e. g. > 16+ will filter out lots of smaller shapes, will result fewer paths. 

```linefilter : true``` will also filter out some noise.

As you mentioned, blur can help, e. g. ```blurradius : 5``` , ```blurdelta : 50``` .

If you want to filter out shapes with specific colors, you can turn off color clustering and set a fixed palette, so the shapes you want to filter out would be "merged" with a neighbor.

For example: let's say you have an input image with red, green and blue shapes and you want to merge blue to green:


```javascript
options = { colorsampling:0, colorquantcycles:1, pathomit:20, blurradius:5, blurdelta: 64, linefilter:true };

options.pal = [ { r:255, g:0, b:0, a:255 }, { r:0, g:255, b:1, a:255 } ];
```

I think this would assign green to the blue pixels in ```colorquantization()``` , but I haven't tested it. :)

**Comment by velara3** [comment]
OK I tested a few of these options. Path omit works but it thins out the image as you say. Blur works but blurs the results obviously. So it seems that reducing the number of colors gives you the desired results with less colors. And if that doesn't reduce enough I think I'll use path omit as secondary option.
