### ISSUE TITLE
Imagetracer & Inkscape extension not working on Fedora 33

### ISSUE THREAD

**Issue by bosd** [jankovicsandras/imagetracerjs#55]
Using Inksacpe extenstion on version 1.0.2
Got an error message on Fedora 32
Python 3.9.2
Installed Pillow version 8.1.2

![image](https://user-images.githubusercontent.com/11499387/111223485-80329f80-85dd-11eb-8340-7c731b36d5ea.png)

**Comment by jankovicsandras** [comment]
Hi,

Please install [Node.js](https://nodejs.org/) and try again.

If this wouldn't work, I recommend sending a message to [Mario Voigt](https://github.com/vmario89), who created the [InkScape plugin](https://github.com/jankovicsandras/imagetracerjs/issues/47).

**Comment by bosd** [comment]
Thanks for the prompt reply.
I went to dig further into the problem. It seems that it is unrelated to inkscape as the module itself is n't working.
I've update to the latest stable node.js.

the feedback is a bit more verbose

```

@fedora imagetracerjs-master]$ sudo node nodecli ../panda.png -outfilename outpanda.svg
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/user/Downloads/imagetracerjs-master2/nodecli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


``

**Comment by jankovicsandras** [comment]
Here's some things that might help/explain, but these are just guessing, I haven't tested it yet:
 - ```nodecli``` is not exported as a module, it's only an example how imagetracerjs works with Node.js, it's not meant to be an application. But it's very simple, I recommend modifying it to fit your needs.
 - Can you check the paths? I see you started the command from ```imagetracerjs-master``` , but it looks for ```nodecli``` in ```imagetracerjs-master2```. Please try from the actual directory which contains ```nodecli```.
 - Please try without ```sudo```, so just ```node nodecli ../panda.png -outfilename outpanda.svg```

**Comment by jankovicsandras** [comment]
Great! I close this, follow up is in Issue #47.
