### ISSUE TITLE
Request of demo - React possibly

### ISSUE THREAD

**Issue by damiano216** [jankovicsandras/imagetracerjs#61]
Is there a demo on how to use the package on react or on vanilla js? Something link a codesandbox... Thanks!

**Comment by jankovicsandras** [comment]
Hi,

From [README.md](https://github.com/jankovicsandras/imagetracerjs/blob/master/README.md) :


## Getting started

### Using in the Browser
Include the script:
```javascript
<script src="imagetracer_v1.2.6.js"></script>
```
Then:
```javascript
// Loading an image, tracing with the 'posterized2' option preset, and appending the SVG to an element with id="svgcontainer"
ImageTracer.imageToSVG(

	'panda.png', /* input filename / URL */
	
	function(svgstr){ ImageTracer.appendSVGString( svgstr, 'svgcontainer' ); }, /* callback function to run on SVG string result */
	
	'posterized2' /* Option preset */
	
);
```


This is vanilla JS in the browser. I'm not a React expert, but I think this should work.

If you are thinking of using imagetracerjs on the server side (for example Node.js) , that should also work, but you might need to load the image to an [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData) object and use the [Synchronous tracing commands](https://github.com/jankovicsandras/imagetracerjs/blob/master/README.md#api). Please look at the [nodecli example](https://github.com/jankovicsandras/imagetracerjs/tree/master/nodecli) for details.

**Comment by jankovicsandras** [comment]
I hope this helped. Feel free to reopen the Issue, if you have more questions.
