### ISSUE TITLE
artifact paths with opacity=0

### ISSUE THREAD

**Issue by chrisyelf** [jankovicsandras/imagetracerjs#62]
Hi,

Thanks so much for this library!

I'm trying to parse the attached png

![bee](https://user-images.githubusercontent.com/121562270/210059777-620acdec-b3a3-4d4f-82ca-fb15d6966255.png)

I've found these options work great to remove noise:
``` 
scale 1 numberofcolors 8 ltres 1 qtres 1 pathomit 128
```

but there are still a few artifact paths with opacity=0 and color white. I've changed opacity to 1 and colors, so they are visible:

![bee-it-obj](https://user-images.githubusercontent.com/121562270/210059942-5b77499d-ada8-4f76-bb18-100ac2b4fca1.svg)

Is there a way to avoid generating these paths? I'm not sure why paths with opacity=0 would be useful to be included.

Thanks again and Happy New Year :)

**Comment by jankovicsandras** [comment]
Hi,

You're right, it's not really useful. But imagetracerjs treats transparency as a color, so it's rendered. (Might be useful if somebody would postprocess the SVG?) 
Anyway, you can try to insert this line

```javascript
if( tracedata.palette[lcnt].a === 0 ){ continue; }
```

between lines [990 - 991](https://github.com/jankovicsandras/imagetracerjs/blob/fd7252f20e5a832adc326fbe4e88b17530d4747e/imagetracer_v1.2.6.js#L990) to omit opacity="0" paths.

Please let me know if this works, I haven't tested it. :)
Happy New Year!

**Comment by chrisyelf** [comment]
Thank you Andras, that did work!

It would be useful to have exclude transparency as an option. 

Happy New Year! :)
