### ISSUE TITLE
Issue with tracing

### ISSUE THREAD

**Issue by blpraveen** [jankovicsandras/imagetracerjs#69]
I have created a [jsfiddle](https://jsfiddle.net/Bl_praveen2004/pxd5nc0f/3/) of image convert to svg.
I am not able generate required svg images. After converted  still shows text . I want only the block in color to be converted to svg not the text and the borders. I did not understand bit about options if possible to tweak. Can you help me?

**Comment by blpraveen** [comment]
Is it possible to ignore type="L" and consider only type="Q"?

**Comment by jankovicsandras** [comment]
Hi,

If you use the 'curvy' option preset or set a very small ltres in [options](https://github.com/jankovicsandras/imagetracerjs/blob/master/options.md), then almost all of the paths will be type Q.

**Comment by blpraveen** [comment]
<img width="383" alt="seating_chart" src="https://github.com/jankovicsandras/imagetracerjs/assets/3274289/f2fb8213-f01d-45fe-8942-ae4b13605611">

I tried curvy option it better than previous generate. I am using above image. it has text in the image. is it possible to skip this as   
well and keep only blocks or rectangles or trapezoid.

**Comment by blpraveen** [comment]
Is it possible to ignore white and black color text?

**Comment by blpraveen** [comment]
I want only the bounding box from convert?

**Comment by jankovicsandras** [comment]
Hi,

The bounding box would be the easiest. I suggest reading [this example](https://github.com/jankovicsandras/imagetracerjs/blob/master/simplify_interop.html) how to loop through layers and paths (You don't need the Simplify parts). Then you can just use the bounding box like this (pseudocode):
```javascript
tracedata.layers[ layernumber ][ pathnumber ].boundingbox == [ topleft_x, topleft_y, bottomright_x, bottomright_y ]
```

**Comment by blpraveen** [comment]
I want Imagetrace data return not only axis but also fill color.

**Comment by jankovicsandras** [comment]
tracedata.palette == [ {r:...,g:...,b:...,a:...}, {r:...,g:...,b:...,a:...}, ... ]
where the number of the color matches the number of the layer, so the first color fills the first layer, the second color fills the secnond, and so on...

**Comment by jankovicsandras** [comment]
I hope these solved your issue. Feel free to reopen, if you have more questions.
