### ISSUE TITLE
gradients 

### ISSUE THREAD

**Issue by tigercoding56** [jankovicsandras/imagetracerjs#71]
i have a image with gradients , is it possible to add support to them (   [they are in svg standart](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients ))
![Screenshot_20231128_152559](https://github.com/jankovicsandras/imagetracerjs/assets/90169211/4d192d6f-2ee2-4063-946a-3a2b01aa1fdc)

**Comment by jankovicsandras** [comment]
Hi,

This is a good question, I'm aware of the gradients in SVG and I thought about supporting them. But the shape finding algorithm is based on solid colors now. Changing this would make ImageTracer very complex.

Workaround: if you have an algorithm to find the gradients, you can replace them with a solid color before tracing, trace, then add the gradients back at the rendering phase. 

I recommend reading the ```tosvgcolorstr``` function at [Line 1015](https://github.com/jankovicsandras/imagetracerjs/blob/cb0c84a309df5e75614d3b5166cdc77a56f12a98/imagetracer_v1.2.6.js#L1015) , then you can probably patch it like this (I haven't tested this) :
```javascript
ImageTracer.tosvgcolorstr = function(c, options){
		return 'fill="'+ my_gradient_here() +'" stroke="'+ my_gradient_here() +'" stroke-width="'+options.strokewidth+'" opacity="'+c.a/255.0+'" ';
	};
```

Can this be a solution for gradients?

**Comment by jankovicsandras** [comment]
I hope this helped. Feel free to reopen the Issue if you have further questions.
