### ISSUE TITLE
Soften sharp path vectors

### ISSUE THREAD

**Issue by KodeMunkie** [jankovicsandras/imagetracerjs#72]
I've been using this library instead of potrace as it's faster and modern but I've found potrace tends to soften/round its paths (correct term?) so they aren't quite so sharp, whereas I'm unable to do this on imagetracerjs.

Is it possible for you to put in an option please, or have I missed an existing option somewhere?

imagetracerjs and potrace comparison respectively (nb. ignore the palette differences, it is the same image but rotated slightly).
<img width="414" alt="imagetracerjs" src="https://github.com/jankovicsandras/imagetracerjs/assets/13253888/5a4171c9-61df-4bd2-bd46-a0d567811e91">

<img width="402" alt="potrace" src="https://github.com/jankovicsandras/imagetracerjs/assets/13253888/657b1160-a9ac-467c-82fe-4cffe9a85e2d">

**Comment by jankovicsandras** [comment]
Hi,

I recommend using the ```curvy``` option preset or setting ```options.ltres = 0.01;``` . See also: https://github.com/jankovicsandras/imagetracerjs/blob/master/options.md

**Comment by KodeMunkie** [comment]
Thanks I've used the ltres option and it's looking very similar now. Amazing software, thanks for making it :)
