### ISSUE TITLE
Hole in transparent image

### ISSUE THREAD

**Issue by Bauzival** [jankovicsandras/imagetracerjs#8]
Hi, I think I have found a bug in your (otherwise great) library: When tracing a transparent black image with a "hole" (transparent area surrounded by black area), the "hole" is colored black in the resulting SVG.
I did not try colored images but it is definitely reproducible on transparent/black images.

Thanks for looking into it.

**Comment by Bauzival** [comment]
You can find an example image here:
https://postimg.org/image/w52h15e6t/

**Comment by jankovicsandras** [comment]
Hi,

Yes, this doesn't work correctly now [(see also Issue #7)](https://github.com/jankovicsandras/imagetracerjs/issues/7). ImageTracer creates hole-free shapes and puts the smaller included shapes on top with pseudo Z-indexing¹.

![https://raw.githubusercontent.com/jankovicsandras/imagetracerjs/master/docimages/transparency_problem.png](https://raw.githubusercontent.com/jankovicsandras/imagetracerjs/master/docimages/transparency_problem.png)

I'm planning to fix this in the next version.

¹ SVG 1.1 has no z-indexing, see [https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements](https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements) . z-index should come in SVG 2, but it's not implemented yet in Firefox [https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_2_support_in_Mozilla#Painting](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_2_support_in_Mozilla#Painting) and possibly not in Google Chrome either: [https://css-tricks.com/svg-2-conundrum/](https://css-tricks.com/svg-2-conundrum/) :(

**Comment by Bauzival** [comment]
Ok, thanks. So there's no workaround for this at the moment? Or can you give me a hint how to achieve such transparent areas? Thanks

**Comment by jankovicsandras** [comment]
Hi,

I have an idea what should be done, but haven't had the time to implement the fix yet.

The holes are actually registered in pathscan(), but then thrown away around [line 416](https://github.com/jankovicsandras/imagetracerjs/blob/master/imagetracer_v1.1.2.js#L416). 

These should be kept instead, somehow propagated through the batch interpolation and tracing steps together with their parent shapes to svgpathstring(), where they should be [rendered counterclockwise together with their parents with fill-rule: evenodd](http://stackoverflow.com/questions/3742479/how-to-cut-a-hole-in-an-svg-rectangle) around [line 633](https://github.com/jankovicsandras/imagetracerjs/blob/master/imagetracer_v1.1.2.js#L633).

I'll be very happy if someone has the time to fix this and send me a pull request. :)

**Comment by jankovicsandras** [comment]
This is fixed in version 1.2.0.
