### ISSUE TITLE
Option blurradius causes error in node.js

### ISSUE THREAD

**Issue by acasaccia** [jankovicsandras/imagetracerjs#9]
If I set `blurradius` to any value higher than the default `0`, I receive the following error:
```
var canvas = document.createElement('canvas');
             ^

ReferenceError: document is not defined
    at ImageTracer.blur
```
It looks like this feature needs the DOM to work. Is there any way to workaround this for use in node.js?

**Comment by acasaccia** [comment]
Managed to get it working by installing `jsdom` and `canvas`.

And creating a document this way:
```
const JSDOM = require("jsdom").JSDOM;
const document = (new JSDOM(`<!DOCTYPE html><p>Hello world</p>`)).window.document;
global.document = document;
```

Once that was done, I was still getting an error:

```
TypeError: Expected (Uint8ClampedArray, width[, height]) or (width, height)
    at TypeError (native)
    at CanvasRenderingContext2D.Context2d.createImageData (C:\Users\Andrea\Code\paint-with-numbers\node_modules\canvas\lib\context2d.js:365:10)
    at ImageTracer.blur (C:\Users\Andrea\Code\paint-with-numbers\node_modules\imagetracerjs\imagetracer_v1.2.0.js:939:23)
```

And to fix that I had to change line 939 from:
`var imgd2 = context.createImageData(imgd);`
to:
`var imgd2 = context.createImageData(imgd.width, imgd.height);`

**Comment by jankovicsandras** [comment]
Hi,

Thank you for reporting this bug and even more for offering a workaround! Great job! I'll try to fix this by removing the DOM and canvas dependencies in blur().

**Comment by jankovicsandras** [comment]
Hi,

Please test whether this fix works for you!

**Comment by acasaccia** [comment]
Node applications now run with `blurradius` without any error, but it looks like `package.json` is still referencing the old library `imagetracer_v1.2.0.js` rather than `imagetracer_v1.2.1.js`.

**Comment by jankovicsandras** [comment]
Npmjs version should be fixed now.
